apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-project.fullname" . }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "demo-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo-project.selectorLabels" . | nindent 4 }}
